project:
  type: website
  resources: 
   - resources/Kevin-Quinteros-Resume.pdf
website:
  title: "Kevin Quinteros"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - blog.qmd
  page-footer:
    left: "© Copyright 2025 Kevin Quinteros. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."
format:
  html:
    theme:
      - cosmo
      - theme/theme-light.scss
    css: styles.css
    toc: false

editor: visual